# This is a basic workflow to help you get started with Actions

name: wip-push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unitteset:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Checkout wip branch
      uses: actions/checkout@v2
      with:
        ref: wip
        path: mvtb
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install spatialmath-python
        python -m pip install opencv-python

        cd ../mvtb/mvtb-data
        python -m pip install .
    - name: Test with pytest
      run: |
        cd mvtb
        pip install pytest-timeout
        pytest --timeout=50 --timeout_method thread -s

